### ISSUE TITLE
ngDatetimepicker timepicker

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#26]
Hi,
I added in your time popup the following ng-show="$options.format.indexOf(\'ss\') > 0 to get that:
![image](https://cloud.githubusercontent.com/assets/12064482/7412686/8c4fbba2-ef45-11e4-9975-8bba8bc66bc6.png)

I need it. I let you see if you can add it but users told me when I ask a format in HH:mm is a little distracting to see ss in the popup.

best regards

**Comment by mehmetotkun** [comment]
Thank you for this important issue. I will find a proper solution for this issue. I have been very busy from 3 weeks.

The distracting problem is due to css animation-duration propery of `.ng-animate` or `button`. You should add `display:none` porperty via style attribute or css. Currently it will solve your case.

**Comment by mehmetotkun** [comment]
solved
