### ISSUE TITLE
CKEditor in Quantum UI Please

### ISSUE THREAD

**Issue by rasekar2000** [quantumui/quantumui#9]
Hello Team,

 http://sysmagazine.com/posts/200058/
  Can we have CKEditor in Quantum UI Component please. Referenced one to you .

Thanks and Regards,
raj

**Comment by mehmetotkun** [comment]
Hi Raj,

Actually we don't want to use third party frameworks or components with QauntumUI which is non-angular or not a set of javascrit utilty. 

If you look at the source, you will find just **moment.js** as third party soulution. Also we have been planing to remove it too. Because, angular has own date service, but need to be enhanced. 

Most of known editors like CKEditor, Tinymce etc. are really powerful components and they keep the market in their hands. However I think they are old technology and they have big size which cannot be used in mobile, tablets etc.

This is a simple comparison of Jquery vs AngularJS to understanding new and old technology.
https://www.airpair.com/angularjs/posts/jquery-angularjs-comparison-migration-walkthrough

In case of an old powerful editor like CKE or TMC. They have custom popoup, custom tooltip, cunstom fonts, custom modal, custom, file api, custom uploader, custom scroller, custom drag-drop etc. This condition cause crowded javascript environment over the page and finally javascript is the worst resource monster of browsers.
 Thus if you need a simple editor, you can use HTML5 contenteditable feature like http://html5demos.com/contenteditable this demo or a simple  **wysiwyg** like https://github.com/TerryMooreII/angular-wysiwyg (you can implement this with QuantumUI)

If you need a complex editor, you can develop one by using http://daringfireball.net/projects/markdown/ 

Or, if you don't have time develop a markdown, you can use one of powerful resource monster. :)

Namely, We don't think use third party soultions in QuantumUI as we can. For our Visual Map and Chart solutions we would use `d3.js` For future, we would have own custom editor solution based on  HTML5 content editable.

**Comment by rasekar2000** [comment]
Hi @mehmetotkun , Thanks for the great explanation.
 I can live with https://github.com/TerryMooreII/angular-wysiwyg for my project. Appreciate your timely pointer. Cheers,
Raj

**Comment by mehmetotkun** [comment]
I'm glad I could help. Please note that you don't need jquery.js, bootstrap.js and bootstrap-color-picker.js if you can edit the code you can build beautiful view by some simple changes. If you can't I can help.
